// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuIn9_NofksdRczgYGTVYeXF2Jg-zfmxY',
    appId: '1:824191321869:web:4c3ac4f020ce3d66f21244',
    messagingSenderId: '824191321869',
    projectId: 'authentication-53f87',
    authDomain: 'authentication-53f87.firebaseapp.com',
    storageBucket: 'authentication-53f87.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm_bw6tcL0qdZ84-Is668icpJHddJKi0Q',
    appId: '1:824191321869:android:75224802d8c9f548f21244',
    messagingSenderId: '824191321869',
    projectId: 'authentication-53f87',
    storageBucket: 'authentication-53f87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHzk_wIQJ8Ay6xtBdRm2CRgvux4f97rNM',
    appId: '1:824191321869:ios:d1819b5c6864931df21244',
    messagingSenderId: '824191321869',
    projectId: 'authentication-53f87',
    storageBucket: 'authentication-53f87.appspot.com',
    iosBundleId: 'com.example.authenticationFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHzk_wIQJ8Ay6xtBdRm2CRgvux4f97rNM',
    appId: '1:824191321869:ios:d1819b5c6864931df21244',
    messagingSenderId: '824191321869',
    projectId: 'authentication-53f87',
    storageBucket: 'authentication-53f87.appspot.com',
    iosBundleId: 'com.example.authenticationFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuIn9_NofksdRczgYGTVYeXF2Jg-zfmxY',
    appId: '1:824191321869:web:32dfac9b7c15b0b0f21244',
    messagingSenderId: '824191321869',
    projectId: 'authentication-53f87',
    authDomain: 'authentication-53f87.firebaseapp.com',
    storageBucket: 'authentication-53f87.appspot.com',
  );
}
